name: tests

on: [push, pull_request]


jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 19

      - name: NPM install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Install playwright browsers
        run: npx playwright install-deps

      - name: Test
        run: npm test
